# Generated by Django 3.2.15 on 2022-09-12 14:23

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('is_coach', models.BooleanField(default=False)),
                ('is_athlete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Name must be greater than 1 character')])),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coach.user')),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Name must be greater than 1 character')])),
                ('dob', models.DateField(null=True, verbose_name='D.O.B')),
                ('gender', models.CharField(blank=True, choices=[(None, 'Choose your gender'), ('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6, verbose_name='gender')),
                ('discipline', models.CharField(blank=True, choices=[(None, 'Choose your primary discipline'), ('kayak', 'kayak'), ('canoe', 'canoe'), ('sup', 'sup'), ('ski', 'ski')], max_length=6, verbose_name='discipline')),
                ('classification', models.CharField(blank=True, choices=[('able-bodied', 'able-bodied'), ('para-canoe', 'para-canoe')], max_length=12, verbose_name='classification')),
                ('club', models.CharField(blank=True, max_length=50, verbose_name='club')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_coach', to='coach.coach')),
            ],
            options={
                'verbose_name_plural': 'Athletes',
            },
        ),
    ]
