# Generated by Django 3.2.15 on 2022-11-25 14:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
