# Generated by Django 3.2.15 on 2022-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(default=1, max_length=20, verbose_name='first name'),
            preserve_default=False,
        ),
    ]
