# Generated by Django 3.2.15 on 2022-11-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_athlete_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
