# Generated by Django 3.2.15 on 2022-11-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20221119_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='username',
        ),
    ]
