# Generated by Django 3.2.15 on 2023-02-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_squadmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squad',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.user'),
            preserve_default=False,
        ),
    ]
