# Generated by Django 3.2.15 on 2022-11-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20221119_2038'),
        ('profiles', '0006_auto_20221119_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.user',),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.user',),
        ),
    ]
