# Generated by Django 3.2.15 on 2022-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COACH', 'Coach'), ('ATHLETE', 'Athlete')], default='COACH', max_length=8),
        ),
    ]
