# Generated by Django 3.2.15 on 2022-10-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220926_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
