# Generated by Django 3.2.15 on 2023-02-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0003_alter_vbo_session_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPeaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('TRAINING', 'Training'), ('STANDALONE', 'Standalone Effort'), ('RACE', 'Racing')], max_length=10)),
                ('data', models.TextField(null=True)),
                ('maxV', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_50m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_100m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_150m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_200m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_300m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_400m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_500m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_750m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_1000m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_1500m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_2000m_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.vbo')),
            ],
        ),
    ]
