# Generated by Django 3.2.15 on 2023-03-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_user_user_name'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPeaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('TRAINING', 'Training'), ('STANDALONE', 'Standalone Effort'), ('RACE', 'Racing')], max_length=10)),
                ('data', models.TextField(null=True)),
                ('maxV', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_50m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_100m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_150m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_200m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_300m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_400m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_500m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_750m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_1000m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_1500m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peak_2000m_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.athlete')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.vbo')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteSessionPeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.athlete')),
                ('session_peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStore.sessionpeaks')),
            ],
            options={
                'unique_together': {('athlete', 'session_peak')},
            },
        ),
    ]
