# Generated by Django 3.2.15 on 2023-02-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpeaks',
            name='maxV',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_1000m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_100m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_1500m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_150m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_2000m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_200m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_300m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_400m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_500m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_50m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessionpeaks',
            name='peak_750m_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
