# Generated by Django 3.2.15 on 2023-02-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20230226_2024'),
        ('dataStore', '0002_auto_20230226_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpeaks',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.athlete'),
        ),
        migrations.CreateModel(
            name='AthleteSessionPeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.athlete')),
                ('session_peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStore.sessionpeaks')),
            ],
            options={
                'unique_together': {('athlete', 'session_peak')},
            },
        ),
    ]
