# Generated by Django 3.2.15 on 2023-02-26 15:09

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbo',
            name='file',
            field=models.FileField(upload_to=uploader.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vbo',
            name='session_date',
            field=models.DateField(),
        ),
    ]
