# Generated by Django 3.2.15 on 2022-11-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='Author',
        ),
    ]
