# Generated by Django 3.2.15 on 2022-11-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effort',
            name='session',
        ),
        migrations.AddField(
            model_name='effort',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='athletes.session'),
            preserve_default=False,
        ),
    ]
