# Generated by Django 3.2.15 on 2022-11-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20221119_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='session',
            name='team',
        ),
        migrations.RemoveField(
            model_name='session',
            name='athlete',
        ),
    ]
