# Generated by Django 3.2.15 on 2022-11-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20221119_2038'),
        ('athletes', '0004_auto_20221119_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.athlete'),
        ),
    ]
