# Generated by Django 3.2.15 on 2022-11-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_session_athlete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name_plural': 'metrics'},
        ),
    ]
