# Generated by Django 3.2.15 on 2022-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletedemo',
            name='age',
        ),
        migrations.AddField(
            model_name='athletedemo',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
