# Generated by Django 3.2.15 on 2022-11-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdemo',
            name='coach',
        ),
        migrations.AddField(
            model_name='coachdemo',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.teamdemo'),
        ),
    ]
