# Generated by Django 3.2.15 on 2022-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20221120_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdemo',
            name='athletes',
            field=models.ManyToManyField(related_name='teams', to='demo.AthleteDemo'),
        ),
        migrations.AlterField(
            model_name='teamdemo',
            name='coaches',
            field=models.ManyToManyField(related_name='teams', to='demo.CoachDemo'),
        ),
    ]
