# Generated by Django 3.2.15 on 2022-12-03 17:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20221120_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athletedemo',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coachdemo',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='athletedemo',
            name='classification',
            field=models.CharField(blank=True, choices=[('0', 'able-bodied'), ('1', 'para-canoe')], max_length=12, verbose_name='classification'),
        ),
        migrations.AddField(
            model_name='athletedemo',
            name='club',
            field=models.CharField(blank=True, max_length=50, verbose_name='club'),
        ),
        migrations.AddField(
            model_name='athletedemo',
            name='discipline',
            field=models.CharField(blank=True, choices=[(None, 'Choose your primary discipline'), ('0', 'kayak'), ('1', 'canoe'), ('2', 'sup')], max_length=6, verbose_name='discipline'),
        ),
        migrations.AddField(
            model_name='athletedemo',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='athlete'),
        ),
        migrations.AddField(
            model_name='coachdemo',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='coachdemo',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='coachdemo'),
        ),
        migrations.AlterField(
            model_name='athletedemo',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=7),
        ),
    ]
