# Generated by Django 3.2.15 on 2022-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20221203_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletedemo',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
